# Maintainer: Patricio A. Rossi (MeduZa) <meduzapat@netscape.net>
# https://github.com/meduzapat/LEDSpicerUI
#
# Version and %changelog are generated by packaging/generate-changelogs.sh
# from CMakeLists.txt and CHANGELOG.md — do not edit them by hand.

Name:           ledspicerui
Version:        0.1.0
Release:        1%{?dist}
Summary:        Graphical configuration editor for LEDSpicer

License:        GPL-3.0-or-later
URL:            https://github.com/meduzapat/LEDSpicerUI
Source0:        %{url}/archive/refs/tags/%{version}.tar.gz#/LEDSpicerUI-%{version}.tar.gz

BuildRequires:  gcc-c++
BuildRequires:  cmake
BuildRequires:  pkgconf
BuildRequires:  gtkmm30-devel >= 3.24
BuildRequires:  tinyxml2-devel >= 6.0
BuildRequires:  glib2-devel
BuildRequires:  libxml2
BuildRequires:  desktop-file-utils

Recommends:     ledspicer

%description
LEDSpicer UI is the visual editor for the LEDSpicer platform. It replaces
hand-editing XML configuration files with a point-and-click interface for
designing control-panel layouts, configuring LED hardware, and managing
profiles and animations for arcade cabinets and interactive projects.

It can drive a running LEDSpicer daemon to test layouts and lights live, and
imports and migrates existing projects.

%prep
%autosetup -n LEDSpicerUI-%{version}

%build
%cmake -DINSTALL_DESKTOP_ENTRY=ON
%cmake_build

%install
%cmake_install

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/org.ledspicer.ui.desktop

%files
%license LICENSE
%doc README.md
%{_bindir}/ledspicerui
%{_datadir}/applications/org.ledspicer.ui.desktop
%{_datadir}/icons/hicolor/scalable/apps/org.ledspicer.ui.svg
%{_datadir}/icons/hicolor/256x256/apps/org.ledspicer.ui.png
%{_datadir}/icons/hicolor/48x48/apps/org.ledspicer.ui.png

%changelog
* Fri Jul 10 2026 Patricio A. Rossi (MeduZa) <meduzapat@netscape.net> - 0.1.0-1
- Added
  - Visual cabinet layout editor with in-place element editing, snap-to-grid, and drag-and-drop placement (#74, #75).
  - Live testing against a running LEDSpicer daemon over real IPC, gated by a central test-readiness check (#60, #83).
  - Configurable test-light timeout for layout testing (#62).
  - Restrictor Test button that drives the rotator binary (#84), and a restrictor-only test mode (#85, #87).
  - Project migration tool that upgrades older projects and reacts to read-only project configs (#90, #95).
  - Core UI assets compiled into the binary as a GResource bundle (#78, #79).
  - Persistence of window and dialog geometry across sessions (#57).
- Changed
  - Refreshed main theme and CSS (#81).
  - Consolidated UI element types and detection logic (#59); renamed Ordenable components to Sortable.
  - Reorganized restrictor images into a dedicated directory (#61).
- Fixed
  - Projects no longer fail to load (empty UI) when opened under a different mode than they were created in (#88).
  - Save validation now rejects invalid data instead of writing it (#89).
  - Fixed a crash when clicking a pin box on the Scattered RGB tab with non-RGB hardware (#80).
  - Layout view and label corrections (#91).
