name: Run Tests

# Trigger on pull requests to master or development
on:
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the PR code
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          xvfb                    \
          build-essential         \
          cmake                   \
          libgtkmm-3.0-dev        \
          libtinyxml2-dev         \
          libgtest-dev

      # Configure and build
      - name: Configure
        run: |
          mkdir target
          cd target
          cmake .. -DCMAKE_CXX_FLAGS="-g3 -O0"

      # Run build
      - name: Build
        run: cmake --build target --target DefaultsTest --target DataTest --target MessageTest --target XMLHelperTest --parallel

      # Run tests
      - name: Run Tests
        run: |
          cd target
          export DISPLAY=:99
          xvfb-run --auto-servernum ctest --output-on-failure
